# Yaas Server Nodeport

apiVersion: v1
kind: Service
metadata:
  name: yaas-server
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: yaas-server
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
      nodePort: 30101
    - name: radiusacct
      protocol: UDP
      port: 1813
      nodePort: 30102
    - name: diameter
      protocol: TCP
      port: 3868
      nodePort: 30201