
# Yaas Superserver radius Service

apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver-radius
spec:
  selector:
    app: yaas-superserver
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
    - name: radiusacct
      protocol: UDP
      port: 1813

---
# Yaas Superserver diameter Service

apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver-diameter
spec:
  clusterIP: None
  selector:
    app: yaas-superserver
  ports:
    - name: diameter
      protocol: TCP
      port: 3868

---
