
# Yaas Superserver Statefulset

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaas-superserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yaas-superserver
  template:
    metadata:
      name: yaas-superserver
      labels:
        app: yaas-superserver
    spec:
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        args: ["clone", "https://github.com/francistor/Yaas.git"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas-db
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8/conf/superserver/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8/conf/superserver/logback-default.xml"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 19000 # Instrumentation
          - containerPort: 19500 # Sessions database
          - containerPort: 1812  # RadiusAuth
          - containerPort: 1813  # RadiusAcct
          - containerPort: 3868  # Diameter
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}

