apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaas-db
spec:
  selector:
    matchLabels:
      app: yaas-db
  serviceName: yaas-db
  replicas: 2
  template:
    metadata:
      labels:
        app: yaas-db
    spec:
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        args: ["clone", "https://github.com/francistor/Yaas.git"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas-db
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8/conf/db/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8/conf/db/logback-default.conf"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 19000 # Instrumentation
          - containerPort: 19500 # Sessions database
          - containerPort: 41000 # Ignite
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}


