apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver
spec:
  selector:
    app: yaas-superserver
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
    - name: radiusacct
      protocol: UDP
      port: 1813
    - name: diameter
      protocol: TCP
      port: 3868
