
# Yaas Database service

apiVersion: v1
kind: Service
metadata:
  namespace: yaas
  name: yaas-db
  labels:
    app: yaas-monitor
spec:
  clusterIP: None
  selector:
    app: yaas-db
  ports:
    - name: monitoring
      protocol: TCP
      port: 19000
    - name: ignite-disc
      port: 47500
    - name: ignite-comm
      port: 47100
    - name: ignite-jdbc
      port: 10800
    - name: ignite-http
      port: 11211
---
    
apiVersion: v1
kind: Service
metadata:
  namespace: yaas
  name: yaas-sessiondb
spec:
  type: NodePort
  selector:
    app: yaas-db
  ports:
    - name: sessions
      protocol: TCP
      port: 19500
      nodePort: 30501
