apiVersion: v1
kind: Pod
metadata:
  name: kagent
  namespace: yaas
spec:
  serviceAccountName: yaas
  containers:
  - name: alpine 
    image: giantswarm/tiny-tools
    command:
      - sleep
      - "3600000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
