apiVersion: v1
kind: Pod
metadata:
  name: kagent
  namespace: yaas
spec:
  containers:
  - name: alpine 
    image: giantswarm/tiny-tools
    command:
      - sleep
      - "360000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
