apiVersion: v1
kind: Namespace
metadata:
  name: yaas
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: yaas
  namespace: yaas
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yaas
  namespace: yaas
rules:
- apiGroups:
  - ""
  resources: 
  - pods
  - endpoints
  verbs: 
  - get
  - list
  - watch
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yaas
roleRef:
  kind: ClusterRole
  name: yaas
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: yaas
  namespace: yaas