apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiusclient
  namespace: yaas
spec:
  replicas: 0
  selector: 
    matchLabels:
      nodeType: radiusclient
  template:
    metadata:
      labels:
        nodeType: radiusclient
        app: yaas-client
    spec:
      serviceAccountName: yaas
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        command: ["/bin/sh", "-c"]
        args: ["git clone https://github.com/francistor/Yaas.git || (cd Yaas; git reset --hard; git pull)"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dinstance=radius", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8s/conf/client/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8s/conf/client/logback-default.xml"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: YAAS_TEST_TYPE
            value: "1"
          - name: YAAS_CONTINUE_ON_PERF_ERROR
            value: "true"
          - name: YAAS_TEST_REQUESTS
            value: "5000"
          - name: YAAS_TEST_LOOP
            value: "true"
          - name: YAAS_TEST_THREADS
            value: "2"
          - name: YAAS_TEST_SERVER_0
            valueFrom:
              configMapKeyRef:
                name: yaas-test-config
                key: YAAS_TEST_SERVER_0
          - name: YAAS_TEST_SERVER_1
            valueFrom:
              configMapKeyRef:
                name: yaas-test-config
                key: YAAS_TEST_SERVER_1
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 19000 # Instrumentation
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}