# Generic server 
apiVersion: v1
kind: Service
metadata:
  name: yaas-server
  labels:
    app: yaas-monitor
spec:
  clusterIP: None
  selector:
    app: yaas-server
  ports:
    - name: monitoring
      protocol: TCP
      port: 19000
---
# Yaas Server for Radius
apiVersion: v1
kind: Service
metadata:
  name: yaas-server-radius
spec:
  type: NodePort
  selector:
    app: yaas-server
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
      nodePort: 30101
    - name: radiusacct
      protocol: UDP
      port: 1813
      nodePort: 30102      
---      
# Yaas Server for Diameter. Node 0
apiVersion: v1
kind: Service
metadata:
  name: yaas-server-diameter-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: yaas-server-0
  ports:   
    - name: diameter
      protocol: TCP
      port: 3868
      nodePort: 30200
--- 
# Yaas Server for Diameter. Node 1
apiVersion: v1
kind: Service
metadata:
  name: yaas-server-diameter-1
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: yaas-server-1
  ports:   
    - name: diameter
      protocol: TCP
      port: 3868
      nodePort: 30201

