apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yaas-monitor
  namespace: yaas
spec:
  jobLabel: yaas-metrics
  selector:
    matchLabels:
      app: yaas-monitor
  namespaceSelector:
    matchNames:
    - yaas
  endpoints:
    - interval: 5s
      targetPort: 19000
