
# Yaas Server Daemonset

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaas-server
  namespace: yaas
spec:
  selector:
    matchLabels:
      app: yaas-server
  replicas: 2
  serviceName: yaas-server
  template:
    metadata:
      name: yaas-server
      labels:
        app: yaas-server
    spec:
      serviceAccountName: yaas
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        command: ["/bin/sh", "-c"]
        args: ["git clone https://github.com/francistor/Yaas.git || (cd Yaas; git reset --hard; git pull)"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8s/conf/server/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8s/conf/server/logback-default.xml"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name    
        readinessProbe:
          httpGet:
            path: /ready
            port: 19000
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
          - containerPort: 19000 # Instrumentation
          - containerPort: 19500 # Sessions database
          - containerPort: 1812  # RadiusAuth
          - containerPort: 1813  # RadiusAcct
          - containerPort: 3868  # Diameter
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}


