apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yaas-server-monitor
  namespace: default
spec:
  jobLabel: yaas-server-metrics
  selector:
    matchLabels:
      app: yaas-monitor
  namespaceSelector:
    matchNames:
    - default
  endpoints:
    - interval: 5s
      targetPort: 19000
