# Yaas Superserver generic (radius, diameter and monitoring for statefulset)
apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver
  namespace: yaas
  labels:
    app: yaas-monitor
spec:
  clusterIP: None
  selector:
    app: yaas-superserver
  ports:
    - name: monitoring
      protocol: TCP
      port: 19000
    - name: diameter
      protocol: TCP
      port: 3868
    - name: radiusauth
      protocol: UDP
      port: 1812
    - name: radiusacct
      protocol: UDP
      port: 1813
---
# Yaas Superserver radius Service

apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver-radius
  namespace: yaas
spec:
  selector:
    app: yaas-superserver
  sessionAffinity: None
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
    - name: radiusacct
      protocol: UDP
      port: 1813

