# Yaas Database Statefulset

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaas-db
spec:
  selector:
    matchLabels:
      app: yaas-db
  serviceName: yaas-db
  replicas: 2
  template:
    metadata:
      labels:
        app: yaas-db
    spec:
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        args: ["clone", "https://github.com/francistor/Yaas.git"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas-db
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8/conf/db/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8/conf/db/logback-default.xml"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 19000 # Instrumentation
          - containerPort: 19500 # Sessions database
          - containerPort: 41000 # Ignite
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}
---
# Yaas Database service

apiVersion: v1
kind: Service
metadata:
  name: yaas-db
spec:
  clusterIP: None
  selector:
    app: yaas-db
    
---
# Yaas Superserver Statefulset

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yaas-superserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yaas-superserver
  template:
    metadata:
      name: yaas-superserver
      labels:
        app: yaas-superserver
    spec:
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        args: ["clone", "https://github.com/francistor/Yaas.git"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas-db
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8/conf/superserver/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8/conf/superserver/logback-default.xml"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 19000 # Instrumentation
          - containerPort: 19500 # Sessions database
          - containerPort: 1812  # RadiusAuth
          - containerPort: 1813  # RadiusAcct
          - containerPort: 3868  # Diameter
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}

---
# Yaas Superserver radius Service

apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver-radius
spec:
  selector:
    app: yaas-superserver
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
    - name: radiusacct
      protocol: UDP
      port: 1813

---
# Yaas Superserver diameter Service

apiVersion: v1
kind: Service
metadata:
  name: yaas-superserver-diameter
spec:
  clusterIP: None
  selector:
    app: yaas-superserver
  ports:
    - name: diameter
      protocol: TCP
      port: 3868

---

# Yaas Server Daemonset

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yaas-server
spec:
  selector:
    matchLabels:
      app: yaas-server
  template:
    metadata:
      name: yaas-server
      labels:
        app: yaas-server
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: git
        image: alpine/git:1.0.7
        args: ["clone", "https://github.com/francistor/Yaas.git"]
        volumeMounts:
          - name: configuration
            mountPath: /git
      containers:
      - name: yaas-db
        image: francistor/yaas:0.1
        command: ["./aaaserver", "-Dconfig.file=/aaaserver/conf/Yaas/src/k8/conf/server/aaa-default.conf", "-Dlogback.configurationFile=/aaaserver/conf/Yaas/src/k8/conf/server/logback-default.xml"]
        volumeMounts:
          - name: configuration
            mountPath: /aaaserver/conf 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 19000 # Instrumentation
          - containerPort: 19500 # Sessions database
          - containerPort: 1812  # RadiusAuth
          - containerPort: 1813  # RadiusAcct
          - containerPort: 3868  # Diameter
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
      volumes:
        - name: configuration
          emptyDir: {}


---
# Yaas Server Nodeport

apiVersion: v1
kind: Service
metadata:
  name: yaas-server
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: yaas-server
  ports:
    - name: radiusauth
      protocol: UDP
      port: 1812
    - name: radiusacct
      protocol: UDP
      port: 1813
    - name: diameter
      protocol: TCP
      port: 3868